// Mocks generated by Mockito 5.0.15 from annotations
// in flutter_clean_architecture/test/core/components/blocs/user/login/login_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i5;
import 'package:flutter_clean_architecture/core/components/data/models/request/login_body.dart'
    as _i8;
import 'package:flutter_clean_architecture/core/components/domains/entities/response/login_model_entity.dart'
    as _i7;
import 'package:flutter_clean_architecture/core/components/domains/repository/user_repository.dart'
    as _i2;
import 'package:flutter_clean_architecture/core/components/domains/usecases/login_usecase.dart'
    as _i3;
import 'package:flutter_clean_architecture/core/exceptions/failure.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeUserRepository_0 extends _i1.Fake implements _i2.UserRepository {}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i3.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeUserRepository_0()) as _i2.UserRepository);
  @override
  _i4.Stream<_i5.Either<_i6.Failure, _i7.LoginModelEntity>> build(
          _i8.LoginBody? params) =>
      (super.noSuchMethod(Invocation.method(#build, [params]),
              returnValue:
                  Stream<_i5.Either<_i6.Failure, _i7.LoginModelEntity>>.empty())
          as _i4.Stream<_i5.Either<_i6.Failure, _i7.LoginModelEntity>>);
  @override
  _i4.Stream<_i5.Either<_i6.Failure, _i7.LoginModelEntity>> execute(
          _i8.LoginBody? params) =>
      (super.noSuchMethod(Invocation.method(#execute, [params]),
              returnValue:
                  Stream<_i5.Either<_i6.Failure, _i7.LoginModelEntity>>.empty())
          as _i4.Stream<_i5.Either<_i6.Failure, _i7.LoginModelEntity>>);
  @override
  String toString() => super.toString();
}
