// Mocks generated by Mockito 5.0.15 from annotations
// in flutter_clean_architecture/test/core/components/domains/usecases/login_usecase_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:dartz/dartz.dart' as _i4;
import 'package:flutter_clean_architecture/core/components/data/models/request/login_body.dart'
    as _i7;
import 'package:flutter_clean_architecture/core/components/domains/entities/response/login_model_entity.dart'
    as _i6;
import 'package:flutter_clean_architecture/core/components/domains/repository/user_repository.dart'
    as _i2;
import 'package:flutter_clean_architecture/core/exceptions/failure.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.Either<_i5.Failure, _i6.LoginModelEntity>> requestLogin(
          _i7.LoginBody? body) =>
      (super.noSuchMethod(Invocation.method(#requestLogin, [body]),
              returnValue:
                  Stream<_i4.Either<_i5.Failure, _i6.LoginModelEntity>>.empty())
          as _i3.Stream<_i4.Either<_i5.Failure, _i6.LoginModelEntity>>);
  @override
  String toString() => super.toString();
}
